version: '3.8'

services:
  api:
    build: .
    container_name: github-auditor-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG_MODE=false
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DATABASE_NAME=/app/data/github_auditor.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data  # Persist database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add Redis for better rate limiting (future enhancement)
#  redis:
#    image: redis:7-alpine
#    container_name: github-auditor-redis
#    ports:
#      - "6379:6379"
#    restart: unless-stopped

volumes:
  data: