"""
email_service.py
Send analysis reports via email
"""

import os
from typing import Dict
from datetime import datetime

# Try to import SendGrid (optional)
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail
    SENDGRID_AVAILABLE = True
except ImportError:
    SENDGRID_AVAILABLE = False

# SendGrid API Configuration
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
FROM_EMAIL = os.getenv('FROM_EMAIL', 'noreply@githubauditor.com')

def generate_email_html(username: str, analysis_data: Dict) -> str:
    """Generate HTML email template for analysis report"""
    
    score = analysis_data.get('authenticity_score', 0)
    red_flags = analysis_data.get('red_flags', [])
    profile = analysis_data.get('profile', {})
    
    # Determine score color
    if score >= 80:
        score_color = '#10b981'
        score_label = 'Authentic'
    elif score >= 50:
        score_color = '#f59e0b'
        score_label = 'Questionable'
    else:
        score_color = '#ef4444'
        score_label = 'Suspicious'
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
            .content {{ background: #f9fafb; padding: 30px; }}
            .score-badge {{ text-align: center; margin: 30px 0; }}
            .score-circle {{ width: 150px; height: 150px; border-radius: 50%; background: {score_color}; color: white; display: inline-flex; align-items: center; justify-content: center; font-size: 48px; font-weight: bold; }}
            .score-label {{ margin-top: 10px; font-size: 24px; font-weight: bold; color: {score_color}; }}
            .section {{ background: white; padding: 20px; margin: 20px 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            .red-flag {{ background: #fee2e2; border-left: 4px solid #ef4444; padding: 12px; margin: 10px 0; border-radius: 4px; }}
            .footer {{ text-align: center; padding: 20px; color: #6b7280; font-size: 14px; }}
            .button {{ display: inline-block; padding: 12px 24px; background: #667eea; color: white; text-decoration: none; border-radius: 6px; margin: 20px 0; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1> GitHub Profile Analysis Report</h1>
                <p>Analysis for: <strong>@{username}</strong></p>
                <p style="font-size: 14px; opacity: 0.9;">{datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
            </div>
            
            <div class="content">
                <div class="score-badge">
                    <div class="score-circle">{score}</div>
                    <div class="score-label">{score_label}</div>
                    <p style="color: #6b7280;">Authenticity Score (out of 100)</p>
                </div>
                
                <div class="section">
                    <h2> Profile Summary</h2>
                    <p><strong>Username:</strong> {profile.get('username', username)}</p>
                    <p><strong>Name:</strong> {profile.get('name', 'N/A')}</p>
                    <p><strong>Public Repos:</strong> {profile.get('public_repos', 0)}</p>
                    <p><strong>Followers:</strong> {profile.get('followers', 0)}</p>
                    <p><strong>Account Created:</strong> {profile.get('created_at', 'N/A')}</p>
                </div>
                
                <div class="section">
                    <h2> Red Flags Detected ({len(red_flags)})</h2>
                    {''.join([f'<div class="red-flag"><strong>{flag.get("type", "Unknown")}</strong>: {flag.get("message", "No description")}</div>' for flag in red_flags]) if red_flags else '<p style="color: #10b981;"> No red flags detected! This profile looks authentic.</p>'}
                </div>
                
                <div class="section">
                    <h2> Recommendation</h2>
                    <p>
                        {'This profile shows strong authenticity indicators. Suitable for consideration.' if score >= 80 
                         else 'This profile has some concerns. Additional verification recommended.' if score >= 50
                         else 'This profile shows significant red flags. Exercise caution.'}
                    </p>
                </div>
                
                <div style="text-align: center;">
                    <a href="https://your-vercel-url.vercel.app/results/{username}" class="button">
                        View Full Report Online
                    </a>
                </div>
            </div>
            
            <div class="footer">
                <p>This report was generated by GitHub Auditor</p>
                <p style="font-size: 12px; color: #9ca3af;">Automated analysis  Not a substitute for human judgment</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html

def send_analysis_email(to_email: str, username: str, analysis_data: Dict) -> bool:
    """
    Send analysis report via email (SendGrid)
    
    Args:
        to_email: Recipient email address
        username: GitHub username analyzed
        analysis_data: Complete analysis data
        
    Returns:
        True if sent successfully, False otherwise
    """
    
    if not SENDGRID_AVAILABLE:
        print("⚠️ SendGrid not installed - Running in DEMO mode")
        print(f"📧 Would send email to: {to_email}")
        print("💡 To enable emails: pip install sendgrid")
        return True
    
    if not SENDGRID_API_KEY:
        print("⚠️ SendGrid API key not configured - Running in DEMO mode")
        print(f"📧 Would send email to: {to_email}")
        print("💡 Set SENDGRID_API_KEY environment variable")
        return True
    
    try:
        # Generate HTML content
        html_content = generate_email_html(username, analysis_data)
        
        # Create email message
        message = Mail(
            from_email=FROM_EMAIL,
            to_emails=to_email,
            subject=f'GitHub Analysis Report: @{username}',
            html_content=html_content
        )
        
        # Send via SendGrid
        print(f"📤 Sending email via SendGrid to {to_email}...")
        sg = SendGridAPIClient(SENDGRID_API_KEY)
        response = sg.send(message)
        
        print(f"✅ Email sent successfully! Status: {response.status_code}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email: {str(e)}")
        return False


# ============================================
# TEST FUNCTION
# ============================================

if __name__ == "__main__":
    # Test the email service
    print("🧪 Testing Email Service...")
    
    test_data = {
        'authenticity_score': 87,
        'red_flags': [
            {'type': 'irregular_commits', 'message': 'Commits concentrated in specific hours'},
        ],
        'profile': {
            'username': 'testuser',
            'name': 'Test User',
            'public_repos': 42,
            'followers': 123,
            'created_at': '2020-01-15'
        }
    }
    
    success = send_analysis_email('test@example.com', 'testuser', test_data)
    print(f"\n✅ Test Result: {'Success' if success else 'Failed'}")
